### ISSUE TITLE
Compatible with Expo SDK36

### ISSUE THREAD

**Issue by JOJ0** [alexishevia/rn-dropbox-filepicker#3]
Hi,
is this package known to be working with expo sdk 36.0.0?
It seems like it's not importing properly in my app. I am fairly new to RN, probably I am doing something wrong.

I imported and declared it as described in your README, except that I export the component and use it somewhere else. That shouldn't matter:

```
export default class ConfigScreen extends React.Component {
...
```

The syntax error thrown, I suppose is just because the component can't be found at all and thus the syntax is screwed:

```
SyntaxError: /Users/jojo/git/react/discodos-2019-12/screens/ConfigScreen.js: Unexpected token, expected "}" (33:66)

  31 |             accessToken={accessToken}
  32 |             filepath={filepath}
> 33 |             onLogin={accessToken => this.setState({ accessToken });}
     |                                                                   ^
  34 |             onLogout={() => this.setState({ accessToken: null, filepath: null });}
  35 |             onFilePick={filepath => this.setState({ filepath });}
  36 |             onError={error => console.error(error.message);}
Failed building JavaScript bundle.
```

yarn add went ok. I just got these dependency warnings, but possibly they don't have anything to do with the issue, not sure...

```
warning " > rn-dropbox-filepicker@0.0.4" has incorrect peer dependency "expo@^33.0.0".
warning " > rn-dropbox-filepicker@0.0.4" has incorrect peer dependency "react-native@^0.60.5".
warning " > rn-dropbox-filepicker@0.0.4" has incorrect peer dependency "react-native-paper@^2.16.0".
```

Another wild guess is that it could have something to do with typescript,  Seems like your code is not typescript. vscode complains about the following in a tool-tip warning (~):

```
module "/Users/jojo/git/react/discodos-2019-12/node_modules/rn-dropbox-filepicker/lib/index"
Could not find a declaration file for module 'rn-dropbox-filepicker'. '/Users/jojo/git/react/discodos-2019-12/node_modules/rn-dropbox-filepicker/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/rn-dropbox-filepicker` if it exists or add a new declaration (.d.ts) file containing `declare module 'rn-dropbox-filepicker';`ts(7016)
```

I read somewhere that expo is picky with this these days, even though non-typescript should still be supported.

I also tried adding a index.d.ts file next to your index.js with the contents suggested by vscode. The error in vscode goes away then but it still doesn't work. Still throws the same syntax error.

Maybe you find the time and point me in the right direction?

Thanks a ton in advance!
Jojo

**Comment by alexishevia** [comment]
Hey @JOJ0 . I don't think you need the `;` at the end of your function definitions.

Try: 
```
onLogin={accessToken => this.setState({ accessToken })}
onLogout={() => this.setState({ accessToken: null, filepath: null })}
onFilePick={filepath => this.setState({ filepath })}
onError={error => console.error(error.message)}
```
Instead of 
```
onLogin={accessToken => this.setState({ accessToken });}
onLogout={() => this.setState({ accessToken: null, filepath: null });}
onFilePick={filepath => this.setState({ filepath });}
onError={error => console.error(error.message);}
```
And see if that helps.

**Comment by JOJ0** [comment]
Hell yeah that was it. So it really _was_ just a syntax error. Couldn't believe that. Did that syntax change in jsx or something recently? Or should your example in README be corrected?
Thanks a ton!

**Comment by alexishevia** [comment]
> Did that syntax change in jsx or something recently? Or should your example in README be corrected?

Good question. I don't know the answer, but I would bet the README code never worked. I'll update it and then close this ticket. Thanks for pointing that out.

**Comment by alexishevia** [comment]
Fixed in https://github.com/alexishevia/rn-dropbox-filepicker/commit/5caac83dd8f576f576d0d69b5e67556f65658ab2
